name: backend
description: Meu amigo secreto - projeto backend.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_modular: ^2.0.1
  postgresql2: ^1.0.3
  json_serializable: ^6.5.3
  build_runner: ^2.3.2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.4.1
  orm: ^2.3.1
  dartz: ^0.10.1
  string_validator: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  mocktail: ^0.3.0
  faker: ^2.0.0
